services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    ports:
      - "32400:32400"
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=1000
      - PLEX_GID=1000
    volumes:
      - /home/rafael/config:/config
      - /home/rafael/media:/media
      - /home/rafael/transcode:/transcode
    restart: unless-stopped